### ISSUE TITLE
Segfault with incremental parsing.

### ISSUE THREAD

**Issue by miscco** [blockchaindev/aho_corasick#7]
I have a usecase, where i parse for the existence of certain keywords and add them incrementally.  

However, i found that the code segfaults when i have a word that matches a previous word plus a number.

``` c++
aho_corasick::trie trie;
trie.parse_text("she");
trie.insert("she");
trie.parse_text("she1");
```

Interestingly this only happens when the parsed word is NOT already inserted. So the following runs fine:

``` c++
aho_corasick::trie trie;
trie.insert("she");
trie.parse_text("she");
trie.parse_text("she1");
```

The culprit seems to be 

``` c++
        ptr next_state(CharType character, bool ignore_root_state) const {
            ptr result = nullptr;
            auto found = d_success.find(character);
            if (found != d_success.end()) {
                result = found->second.get();
            } else if (!ignore_root_state && d_root != nullptr) {
                result = d_root;
            }
            return result;
        }
```

where d_success.find(character) segfaults when searching for the number

**Comment by miscco** [comment]
I find, that it doesnt have to be a number. this also fails:

``` c++
    aho_corasick::trie trie;
    trie.insert("hers");
    trie.insert("his");
    trie.insert("he");
    auto result = trie.parse_text("she");
    trie.insert("she");
    result = trie.parse_text("something");
```

**Comment by cjgdev** [comment]
Please provide details of your platform, compiler and environment.

**Comment by webcoyote** [comment]
I believe this is an algorithmic bug, not a platform/environment/compiler issue (but for reference I'm using Windows 10 64-bit, MSVC 14.0.25431.01 -- Microsoft Visual Studio Community 2015, no special env vars set).

After adding a new string to the trie the "d_constructed_failure_states" is still set to true, and I think that is the bug. If I add:

    d_constructed_failure_states = false;

to the end of the `basictrie::insert` function the problem is fixed.
